/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.onboarding.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DrivingData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2959363588721900987L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DrivingData\",\"namespace\":\"com.onboarding.avro\",\"fields\":[{\"name\":\"carTypeId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"distance\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DrivingData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DrivingData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DrivingData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DrivingData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DrivingData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DrivingData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DrivingData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DrivingData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DrivingData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence carTypeId;
  private long timestamp;
  private double distance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DrivingData() {}

  /**
   * All-args constructor.
   * @param carTypeId The new value for carTypeId
   * @param timestamp The new value for timestamp
   * @param distance The new value for distance
   */
  public DrivingData(java.lang.CharSequence carTypeId, java.lang.Long timestamp, java.lang.Double distance) {
    this.carTypeId = carTypeId;
    this.timestamp = timestamp;
    this.distance = distance;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return carTypeId;
    case 1: return timestamp;
    case 2: return distance;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: carTypeId = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: distance = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'carTypeId' field.
   * @return The value of the 'carTypeId' field.
   */
  public java.lang.CharSequence getCarTypeId() {
    return carTypeId;
  }


  /**
   * Sets the value of the 'carTypeId' field.
   * @param value the value to set.
   */
  public void setCarTypeId(java.lang.CharSequence value) {
    this.carTypeId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'distance' field.
   * @return The value of the 'distance' field.
   */
  public double getDistance() {
    return distance;
  }


  /**
   * Sets the value of the 'distance' field.
   * @param value the value to set.
   */
  public void setDistance(double value) {
    this.distance = value;
  }

  /**
   * Creates a new DrivingData RecordBuilder.
   * @return A new DrivingData RecordBuilder
   */
  public static com.onboarding.avro.DrivingData.Builder newBuilder() {
    return new com.onboarding.avro.DrivingData.Builder();
  }

  /**
   * Creates a new DrivingData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DrivingData RecordBuilder
   */
  public static com.onboarding.avro.DrivingData.Builder newBuilder(com.onboarding.avro.DrivingData.Builder other) {
    if (other == null) {
      return new com.onboarding.avro.DrivingData.Builder();
    } else {
      return new com.onboarding.avro.DrivingData.Builder(other);
    }
  }

  /**
   * Creates a new DrivingData RecordBuilder by copying an existing DrivingData instance.
   * @param other The existing instance to copy.
   * @return A new DrivingData RecordBuilder
   */
  public static com.onboarding.avro.DrivingData.Builder newBuilder(com.onboarding.avro.DrivingData other) {
    if (other == null) {
      return new com.onboarding.avro.DrivingData.Builder();
    } else {
      return new com.onboarding.avro.DrivingData.Builder(other);
    }
  }

  /**
   * RecordBuilder for DrivingData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DrivingData>
    implements org.apache.avro.data.RecordBuilder<DrivingData> {

    private java.lang.CharSequence carTypeId;
    private long timestamp;
    private double distance;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.onboarding.avro.DrivingData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.carTypeId)) {
        this.carTypeId = data().deepCopy(fields()[0].schema(), other.carTypeId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.distance)) {
        this.distance = data().deepCopy(fields()[2].schema(), other.distance);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing DrivingData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.onboarding.avro.DrivingData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.carTypeId)) {
        this.carTypeId = data().deepCopy(fields()[0].schema(), other.carTypeId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.distance)) {
        this.distance = data().deepCopy(fields()[2].schema(), other.distance);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'carTypeId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCarTypeId() {
      return carTypeId;
    }


    /**
      * Sets the value of the 'carTypeId' field.
      * @param value The value of 'carTypeId'.
      * @return This builder.
      */
    public com.onboarding.avro.DrivingData.Builder setCarTypeId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.carTypeId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'carTypeId' field has been set.
      * @return True if the 'carTypeId' field has been set, false otherwise.
      */
    public boolean hasCarTypeId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'carTypeId' field.
      * @return This builder.
      */
    public com.onboarding.avro.DrivingData.Builder clearCarTypeId() {
      carTypeId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.onboarding.avro.DrivingData.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.onboarding.avro.DrivingData.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'distance' field.
      * @return The value.
      */
    public double getDistance() {
      return distance;
    }


    /**
      * Sets the value of the 'distance' field.
      * @param value The value of 'distance'.
      * @return This builder.
      */
    public com.onboarding.avro.DrivingData.Builder setDistance(double value) {
      validate(fields()[2], value);
      this.distance = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'distance' field has been set.
      * @return True if the 'distance' field has been set, false otherwise.
      */
    public boolean hasDistance() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'distance' field.
      * @return This builder.
      */
    public com.onboarding.avro.DrivingData.Builder clearDistance() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DrivingData build() {
      try {
        DrivingData record = new DrivingData();
        record.carTypeId = fieldSetFlags()[0] ? this.carTypeId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.distance = fieldSetFlags()[2] ? this.distance : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DrivingData>
    WRITER$ = (org.apache.avro.io.DatumWriter<DrivingData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DrivingData>
    READER$ = (org.apache.avro.io.DatumReader<DrivingData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.carTypeId);

    out.writeLong(this.timestamp);

    out.writeDouble(this.distance);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.carTypeId = in.readString(this.carTypeId instanceof Utf8 ? (Utf8)this.carTypeId : null);

      this.timestamp = in.readLong();

      this.distance = in.readDouble();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.carTypeId = in.readString(this.carTypeId instanceof Utf8 ? (Utf8)this.carTypeId : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.distance = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










